name: Node.js Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

  check-version:
    needs: build
    uses: ./.github/workflows/npm-check.yml

  publish-pkg:
    needs: [build, check-version]
    if: needs.check-version.outputs.already_published == 'false'
    uses: ./.github/workflows/npm-publish-reusable.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  summary-skipped:
    needs: check-version
    if: needs.check-version.outputs.already_published == 'true'
    uses: ./.github/workflows/npm-summary.yml
    with:
      package_name: ${{ needs.check-version.outputs.package_name }}
      before_version: ${{ needs.check-version.outputs.before_version }}
      after_version: ${{ needs.check-version.outputs.before_version }}
      status: "⚠️ Skipped (Version ${{ needs.check-version.outputs.package_version }} is already published on NPM)"

  summary-published:
    needs: [check-version, publish-pkg]
    if: always() && needs.check-version.outputs.already_published == 'false' && needs.publish-pkg.result == 'success'
    uses: ./.github/workflows/npm-summary.yml
    with:
      package_name: ${{ needs.check-version.outputs.package_name }}
      before_version: ${{ needs.check-version.outputs.before_version }}
      after_version: ${{ needs.check-version.outputs.package_version }}
      status: "✅ Successfully Published to NPM"

  notify-dependents:
    needs: [check-version, publish-pkg]
    if: always() && needs.check-version.outputs.already_published == 'false' && needs.publish-pkg.result == 'success'
    uses: ./.github/workflows/notify.yml
    with:
      package_name: ${{ needs.check-version.outputs.package_name }}
      repositories: "keshavsoft/express-fix-endpoints-get-js keshavsoft/template-provider"
    secrets:
      REPO_DISPATCH_TOKEN: ${{ secrets.REPO_DISPATCH_TOKEN }}
